"""Script generation from extracted pages: what is written, and what is never written."""

import ast
import json

import pytest

from healix import GenerationError, ScriptGenerator
from healix.discovery.manifest import FAILED, PENDING, Manifest
from healix.events import EVENT_DATA_FIELDS
from healix.generation import BACKENDS, STYLES
from tests.elements import el
from tests.generation.pages import BASE, write_run

SAFE_IMPORTS = {
    "__future__",
    "collections",
    "contextlib",
    "dotenv",
    "healix",
    "os",
    "pytest",
    "urllib",
}
COMBINATIONS = [(b, s) for b in BACKENDS for s in STYLES]


@pytest.fixture
def manifest(tmp_path):
    return write_run(tmp_path / "output")


def generate(manifest, backend="playwright", style="pom", **kwargs):
    kwargs.setdefault("record_fingerprints", False)
    return ScriptGenerator(manifest, **kwargs).generate(backend, style)


def imports_of(source):
    tree = ast.parse(source)
    found = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            found.update(a.name.split(".")[0] for a in node.names)
        elif isinstance(node, ast.ImportFrom) and node.level == 0:
            found.add((node.module or "").split(".")[0])
    return found


# --- every backend and style ------------------------------------------------------------------- #


@pytest.mark.parametrize(("backend", "style"), COMBINATIONS)
def test_every_backend_and_style_gives_valid_python(manifest, backend, style):
    script = generate(manifest, backend, style)
    ast.parse(script.source)
    assert (script.backend, script.style) == (backend, style)
    assert script.file_path is None  # nothing is written unless asked
    assert "generated by Healix" in script.source


@pytest.mark.parametrize(("backend", "style"), COMBINATIONS)
def test_generated_code_goes_through_healix_and_never_imports_a_browser_library(
    manifest, backend, style
):
    imported = imports_of(generate(manifest, backend, style).source)
    assert "healix" in imported
    assert not imported & {"playwright", "selenium"}


def test_the_backend_only_changes_which_adapter_is_used(manifest):
    playwright = generate(manifest, "playwright", "action").source
    selenium = generate(manifest, "selenium", "action").source
    assert "PlaywrightDriverAdapter" in playwright and "Selenium" not in playwright
    assert "SeleniumDriverAdapter" in selenium and "Playwright" not in selenium
    assert playwright.replace("Playwright", "X").count("run_login") == selenium.count("run_login")


def test_output_is_deterministic(manifest):
    assert generate(manifest).source == generate(manifest).source


# --- the three styles -------------------------------------------------------------------------- #


def test_pom_has_a_class_per_page_and_a_method_per_element(manifest):
    source = generate(manifest, style="pom").source
    for name in ("class LoginPage:", "class OrdersNewPage:", "class HomePage:"):
        assert name in source
    for method in (
        "def fill_login_username(",
        "def fill_password(",
        "def click_remember(",
        "def click_sign_in(",
        "def click_forgot_password(",
        "def fill_email(",
        "def click_save_order(",
    ):
        assert method in source
    assert "def open(self)" in source


def test_controls_that_cannot_be_typed_into_are_located_not_filled(manifest):
    source = generate(manifest, style="pom").source
    assert "def locate_locked(" in source  # read-only
    assert "def locate_frozen(" in source  # disabled
    assert "def fill_locked" not in source and "def fill_frozen" not in source


def test_test_style_asserts_and_never_types_or_clicks(manifest):
    source = generate(manifest, style="test").source
    assert "def test_login(" in source and "def test_orders_new(" in source
    assert "assert" in source and "pytest" in source
    assert ".write(" not in source and ".click(" not in source
    assert 'path.rstrip("/") == "/orders/new"' in source


def test_action_style_fills_then_submits_and_asserts_nothing(manifest):
    source = generate(manifest, style="action").source
    assert not [n for n in ast.walk(ast.parse(source)) if isinstance(n, ast.Assert)]
    login = source[source.index("def run_login") : source.index("def run_orders_new")]
    assert login.index(".write(") < login.index(".click(")
    assert "textbox:login-username" in login and "button:sign-in" in login
    assert "checkbox:remember" not in login  # only inputs are filled, and the submit is clicked
    assert "def run_home" not in source  # a page with nothing to fill has nothing to do


def test_action_style_needs_something_to_fill(tmp_path):
    only_links = write_run(tmp_path, {f"{BASE}/": ("nav_shell", lambda: [el("a", href="/x")])})
    with pytest.raises(GenerationError, match="input to fill"):
        generate(only_links, style="action")


# --- credentials and the fingerprint database -------------------------------------------------- #


def test_login_values_come_from_the_environment_never_from_the_page(manifest):
    source = generate(manifest, style="action").source
    assert 'os.environ["WEBLIB_LOGIN_USERNAME"]' in source
    assert 'os.environ["WEBLIB_LOGIN_PASSWORD"]' in source
    assert "load_dotenv()" in source
    assert "hunter2-do-not-leak" not in source
    assert "hunter2-do-not-leak" not in generate(manifest, style="pom").source


def test_a_test_script_types_nothing_so_it_reads_no_credentials(manifest):
    source = generate(manifest, style="test").source
    assert "os.environ" not in source and "dotenv" not in source


def test_sample_values_follow_the_input_type(manifest):
    source = generate(manifest, style="action").source
    assert '"user@example.com"' in source  # type=email
    assert '"sample text"' in source  # a textarea


def test_the_database_defaults_to_a_local_file_and_a_given_path_is_used(manifest):
    assert 'FINGERPRINT_DB = "healix.db"' in generate(manifest).source
    source = generate(manifest, fingerprint_db="data/fp.db").source
    assert 'FINGERPRINT_DB = "data/fp.db"' in source


def test_a_database_url_is_never_written_into_the_script(manifest):
    url = "postgresql://healix:s3cret-pw@db.example.test:5432/healix"
    source = generate(manifest, fingerprint_db=url).source
    assert "s3cret-pw" not in source and "db.example.test" not in source
    assert 'os.environ["HEALIX_FINGERPRINT_DB"]' in source


def test_fingerprints_are_recorded_for_the_scripts_to_heal_against(manifest, tmp_path):
    from healix import SQLiteFingerprintStore

    db = tmp_path / "fp.db"
    ScriptGenerator(manifest, fingerprint_db=db).to_playwright(style="pom")
    with SQLiteFingerprintStore(db) as store:
        roles = {f.element_role for f in store.fingerprints(f"{BASE}/login")}
    assert roles == {
        "textbox:login-username",
        "textbox:password",
        "checkbox:remember",
        "button:sign-in",
        "link:forgot-password",
    }


def test_recording_can_be_switched_off(manifest, tmp_path):
    db = tmp_path / "fp.db"
    generate(manifest, fingerprint_db=db)  # record_fingerprints=False in the helper
    assert not db.exists()


# --- hostile page content ---------------------------------------------------------------------- #


def test_text_from_the_page_cannot_inject_code(tmp_path):
    hostile = 'x"); import os; os.system("boom"); ("'
    elements = [
        el("input", name="q", type="text", aria_label=hostile, data_testid=hostile),
        el("button", text=hostile, type="submit"),
    ]
    url = f"{BASE}/a\"b'c\\d\n/e"
    manifest = write_run(tmp_path, {url: ("form\nimport os", elements)})
    for backend, style in COMBINATIONS:
        source = generate(manifest, backend, style).source
        tree = ast.parse(source)
        calls = [
            n.func.attr
            for n in ast.walk(tree)
            if isinstance(n, ast.Call) and isinstance(n.func, ast.Attribute)
        ]
        assert "system" not in calls
        assert imports_of(source) <= SAFE_IMPORTS


# --- names ------------------------------------------------------------------------------------- #


def test_pages_and_elements_with_the_same_name_are_told_apart(tmp_path):
    same = lambda: [el("button", text="Save"), el("button", text="Save")]  # noqa: E731
    manifest = write_run(
        tmp_path,
        {f"{BASE}/login": ("form", same), f"{BASE}/other/login": ("form", same)},
    )
    source = generate(manifest, style="pom").source
    classes = [n.name for n in ast.walk(ast.parse(source)) if isinstance(n, ast.ClassDef)]
    assert classes == ["LoginPage", "OtherLoginPage"]
    assert "def click_save(" in source and "def click_save_2(" in source
    ast.parse(source)


def test_a_url_with_no_useful_path_still_gets_a_valid_name(tmp_path):
    manifest = write_run(tmp_path, {f"{BASE}/123": ("form", lambda: [el("button", text="Go")])})
    source = generate(manifest, style="pom").source
    ast.parse(source)
    assert "class Item123Page:" in source


# --- reading the pages ------------------------------------------------------------------------- #


def test_only_extracted_pages_are_scripted_and_the_rest_are_reported(tmp_path):
    manifest_path = write_run(tmp_path, status=PENDING)
    with pytest.raises(GenerationError, match="none of the pages is extracted"):
        generate(manifest_path)

    manifest_path = write_run(tmp_path / "mixed")
    manifest = Manifest.load(manifest_path)
    manifest.pages[1].status = FAILED
    manifest.save(manifest_path)
    script = generate(manifest_path)
    assert script.page_count == 2
    assert script.skipped == ((f"{BASE}/orders/new", "status is failed"),)


def test_a_page_file_outside_the_output_directory_is_not_read(tmp_path):
    manifest_path = write_run(tmp_path / "output")
    secret = tmp_path / "secret.json"
    secret.write_text(json.dumps({"url": f"{BASE}/x", "elements": [el("button").to_dict()]}))
    manifest = Manifest.load(manifest_path)
    manifest.pages[0].output_file = "../secret.json"
    manifest.save(manifest_path)
    script = generate(manifest_path)
    assert script.page_count == 2
    assert "outside the output directory" in script.skipped[0][1]
    assert "secret" not in script.source


def test_a_damaged_page_file_is_skipped_not_fatal(tmp_path):
    manifest_path = write_run(tmp_path)
    (tmp_path / "pages" / "0002.json").write_text("{not json")
    script = generate(manifest_path)
    assert script.page_count == 2
    assert script.skipped[0][0] == f"{BASE}/orders/new"


def test_the_redirected_address_is_what_a_test_expects(tmp_path):
    manifest_path = write_run(
        tmp_path, {f"{BASE}/start": ("form", lambda: [el("button", text="Go")])}
    )
    page = tmp_path / "pages" / "0001.json"
    document = json.loads(page.read_text())
    document["final_url"] = f"{BASE}/landing/"
    page.write_text(json.dumps(document))
    source = generate(manifest_path, style="test").source
    assert '== "/landing"' in source


def test_a_page_limit_leaves_the_rest_out_and_says_so(tmp_path):
    many = lambda: [el("button", text=f"Item {i}") for i in range(30)]  # noqa: E731
    script = generate(
        write_run(tmp_path, {f"{BASE}/big": ("list", many)}), max_elements_per_page=10
    )
    assert script.element_count == 10 and script.truncated == 20


def test_sources_a_generator_accepts(tmp_path):
    manifest_path = write_run(tmp_path)
    manifest = Manifest.load(manifest_path)
    from_path = generate(manifest_path).source
    assert generate(manifest, base_dir=tmp_path).source == from_path
    assert generate(manifest.pages, base_dir=tmp_path).source == from_path
    with pytest.raises(GenerationError, match="no manifest"):
        generate(tmp_path / "missing.json")
    with pytest.raises(GenerationError, match="expected a Run"):
        generate([1, 2])


def test_bad_arguments_are_refused(manifest):
    with pytest.raises(GenerationError, match="backend"):
        generate(manifest, "cypress")
    with pytest.raises(GenerationError, match="style"):
        generate(manifest, style="bdd")
    with pytest.raises(GenerationError, match="at least 1"):
        ScriptGenerator(manifest, max_elements_per_page=0)


# --- writing and events ------------------------------------------------------------------------ #


@pytest.mark.parametrize(
    ("style", "filename"),
    [
        ("pom", "pages_selenium.py"),
        ("test", "test_healix_selenium.py"),
        ("action", "actions_selenium.py"),
    ],
)
def test_output_directory_gets_a_file_named_for_its_style(manifest, tmp_path, style, filename):
    out = tmp_path / "scripts"
    script = ScriptGenerator(manifest, record_fingerprints=False).to_selenium(style, output=out)
    assert script.file_path == out / filename
    assert (out / filename).read_text() == script.source
    assert not [p for p in out.iterdir() if p.name.endswith(".tmp")]


def test_output_can_name_the_file_itself(manifest, tmp_path):
    target = tmp_path / "deep" / "my_pages.py"
    script = ScriptGenerator(manifest, record_fingerprints=False).to_playwright(output=target)
    assert script.file_path == target and target.exists()


def test_a_script_generated_event_matches_the_shared_schema(manifest, tmp_path):
    events = []
    script = ScriptGenerator(manifest, record_fingerprints=False, on_event=events.append)
    result = script.to_playwright("pom", output=tmp_path)
    assert result.element_count == 11
    [event] = events
    assert event["event"] == "script_generated" and event["run_id"] == "run-1"
    assert set(event["data"]) == set(EVENT_DATA_FIELDS["script_generated"])
    assert event["data"] == {
        "backend": "playwright",
        "style": "pom",
        "file_path": str(result.file_path),
        "element_count": 11,  # 5 on the login page, 5 on the order form, 1 link on the home page
    }


def test_the_event_goes_to_a_webhook_too(manifest, webhook_receiver):
    ScriptGenerator(
        manifest, record_fingerprints=False, webhook_url=webhook_receiver.url
    ).to_playwright()
    [payload] = webhook_receiver.payloads
    assert payload["event"] == "script_generated" and payload["data"]["file_path"] is None


# --- a script pointed at a database with nothing in it ---------------------------------------- #


def test_a_database_with_no_fingerprints_for_the_pages_is_warned_about(manifest, tmp_path):
    """The crawl recorded into one database and the script points at another: say so now."""
    missing = generate(
        manifest, fingerprint_db=tmp_path / "nowhere.db"
    )  # record_fingerprints=False
    assert len(missing.warnings) == 1 and "no fingerprints" in missing.warnings[0]
    assert not (tmp_path / "nowhere.db").exists()  # checking must not create it

    from healix import SQLiteFingerprintStore

    with SQLiteFingerprintStore(tmp_path / "empty.db"):
        pass
    assert generate(manifest, fingerprint_db=tmp_path / "empty.db").warnings


def test_no_warning_once_fingerprints_exist_or_are_being_recorded(manifest, tmp_path):
    db = tmp_path / "fp.db"
    recorded = ScriptGenerator(manifest, fingerprint_db=db).to_playwright()
    assert recorded.warnings == ()
    assert generate(manifest, fingerprint_db=db).warnings == ()  # already there, not re-recorded


def test_a_database_url_is_not_connected_to_just_to_warn(manifest):
    url = "postgresql://healix:pw@unreachable.invalid:5432/healix"
    assert generate(manifest, fingerprint_db=url).warnings == ()
